import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import axiosClient from '@/apis/axiosInstance';
import * as console from 'console';

export async function getStaticProps({ locale }: never) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['index'])),
    },
  };
}

export default function Home() {
  const { t } = useTranslation('index');
  const { isLoading, data } = useQuery([], async () => {
    return await axiosClient.get('/').catch((err) => {
      console.error(err);
      return err;
    });
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{t('h1')}</h1>
        <p>{t('description')}</p>
        <div>
          <Link href="/" locale="ko">
            <button>한국어</button>
          </Link>
          <Link href="/" locale="en">
            <button>영어</button>
          </Link>
        </div>
      </main>
    </>
  );
}
